### PR TITLE
Fixed warnings for cocoapods support

### PR DESCRIPTION
**Pull request by robocopklaus**
Hey, nice updates. Sorry it took me so long. You just need to tag your current commit to 1.0.8 and you're good to go.

### CODE REVIEW

**Comment by renebigot** [comment]
Meged ! Thanx !

**Comment by robocopklaus** [comment]
Don't forget to tag the commit to 1.0.8 and push with tags

**Comment by renebigot** [comment]
I've tagged a 1.0.9 with your commits. I'll tag the next versions ;)

**Comment by robocopklaus** [comment]
Awesome! Thanks

**Comment by renebigot** [comment]
You're welcome

**Pull request merged**
